name: gsheets_example

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  gsheets_builder:
    path: ../gsheets_builder/

dev_dependencies:
  build_runner: 1.12.2
  flutter_test:
    sdk: flutter
  gsheets_builder_generator:
    path: ../gsheets_builder_generator/